// Code generated by ryegen; DO NOT EDIT.
package main

import (
	_ "fyne.io/fyne/v2"
	_ "fyne.io/fyne/v2/app"
	_ "fyne.io/fyne/v2/canvas"
	_ "fyne.io/fyne/v2/container"
	_ "fyne.io/fyne/v2/data/binding"
	_ "fyne.io/fyne/v2/data/validation"
	_ "fyne.io/fyne/v2/dialog"
	_ "fyne.io/fyne/v2/driver"
	_ "fyne.io/fyne/v2/driver/desktop"
	_ "fyne.io/fyne/v2/driver/mobile"
	_ "fyne.io/fyne/v2/driver/software"
	_ "fyne.io/fyne/v2/lang"
	_ "fyne.io/fyne/v2/layout"
	_ "fyne.io/fyne/v2/storage"
	_ "fyne.io/fyne/v2/storage/repository"
	_ "fyne.io/fyne/v2/test"
	_ "fyne.io/fyne/v2/theme"
	_ "fyne.io/fyne/v2/widget"
)
