[[target]]
cgo-enabled = true

[[source]]
packages = [
    'fyne.io/fyne/v2',
    'fyne.io/fyne/v2/app',
    'fyne.io/fyne/v2/canvas',
    'fyne.io/fyne/v2/container',
    'fyne.io/fyne/v2/data/binding',
    'fyne.io/fyne/v2/data/validation',
    'fyne.io/fyne/v2/dialog',
    'fyne.io/fyne/v2/driver',
    'fyne.io/fyne/v2/driver/desktop',
    'fyne.io/fyne/v2/driver/mobile',
    'fyne.io/fyne/v2/driver/software',
    'fyne.io/fyne/v2/lang',
    'fyne.io/fyne/v2/layout',
    'fyne.io/fyne/v2/storage',
    'fyne.io/fyne/v2/storage/repository',
    'fyne.io/fyne/v2/test',
    'fyne.io/fyne/v2/theme',
    'fyne.io/fyne/v2/widget',
]

[[rule]]
select = { package = 'fyne\.io/fyne/v2(/.*|)' }
action.set-package = 'fyne\1'

[[rule]]
select = { package = 'fyne(/.*|)', type = 'constructor' }
action.include = false

[[rule]]
action.to-casing = 'kebab'

[[rule]]
select = { package = 'fyne/container', name = 'new-([vh])-(.*)' }
action.rename = 'new-\1\2'

[[rule]]
select.package = 'fyne(/app|/canvas|/container|/data/binding|/data/validation|/dialog|/lang|/layout|/storage|/storage/repository|/theme|/widget|)'
select.name = 'new-(.*)'
action.rename = '\2'